name: Reveal Secret
on: workflow_dispatch # Allows you to run this manually

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Base64 Encode Secret
        run: |
          echo "${{ secrets.YOUR_SECRET_NAME }}" | rev | base64
